[package]
name = "RustlessPass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
zxcvbn = "2.2.2"
time = "0.3.30"
js-sys = "0.3.64"
web-sys = { version = "0.3", features = ["Event","EventTarget","InputEvent"] }
wasm-bindgen = "0.2"
chrono = { version = "0.4", features = ["wasmbind"] }
hex = "0.4.3"
# lesspass = "0.4.0"
sha2 = "0.10.6"
lesspass = { path = "./lib/lesspass.rs" }